var searchData=
[
  ['same_5ftype',['same_type',['../structnvbio_1_1same__type.html',1,'nvbio']]],
  ['same_5ftype_3c_20t_2c_20t_20_3e',['same_type&lt; T, T &gt;',['../structnvbio_1_1same__type_3_01T_00_01T_01_4.html',1,'nvbio']]],
  ['samoutput',['SamOutput',['../structnvbio_1_1io_1_1SamOutput.html',1,'nvbio::io']]],
  ['scan_5fdispatch',['scan_dispatch',['../structnvbio_1_1cuda_1_1scan__dispatch.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_2016_20_3e',['scan_dispatch&lt; T, Op, 16 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01T_00_01Op_00_0116_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_202_20_3e',['scan_dispatch&lt; T, Op, 2 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01T_00_01Op_00_012_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_2032_20_3e',['scan_dispatch&lt; T, Op, 32 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01T_00_01Op_00_0132_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_204_20_3e',['scan_dispatch&lt; T, Op, 4 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01T_00_01Op_00_014_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_208_20_3e',['scan_dispatch&lt; T, Op, 8 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01T_00_01Op_00_018_01_4.html',1,'nvbio::cuda']]],
  ['scoped_5ftimer',['Scoped_timer',['../structnvbio_1_1Scoped__timer.html',1,'nvbio']]],
  ['scopedlock',['ScopedLock',['../classnvbio_1_1ScopedLock.html',1,'nvbio']]],
  ['scorematrices',['ScoreMatrices',['../structnvbio_1_1aln_1_1ScoreMatrices.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3aeditdistancetag_20_3e',['ScoreMatrices&lt; N, M, aln::EditDistanceTag &gt;',['../structnvbio_1_1aln_1_1ScoreMatrices_3_01N_00_01M_00_01aln_1_1EditDistanceTag_01_4.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3agotohtag_20_3e',['ScoreMatrices&lt; N, M, aln::GotohTag &gt;',['../structnvbio_1_1aln_1_1ScoreMatrices_3_01N_00_01M_00_01aln_1_1GotohTag_01_4.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3asmithwatermantag_20_3e',['ScoreMatrices&lt; N, M, aln::SmithWatermanTag &gt;',['../structnvbio_1_1aln_1_1ScoreMatrices_3_01N_00_01M_00_01aln_1_1SmithWatermanTag_01_4.html',1,'nvbio::aln']]],
  ['scorestream',['ScoreStream',['../structnvbio_1_1aln_1_1ScoreStream.html',1,'nvbio::aln']]],
  ['scoringqueues',['ScoringQueues',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringQueues.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringqueuesdeviceview',['ScoringQueuesDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringQueuesDeviceView.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemeselector',['ScoringSchemeSelector',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeSelector.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemeselector_3c_20edit_5fdistance_5fscoring_5ftag_20_3e',['ScoringSchemeSelector&lt; edit_distance_scoring_tag &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeSelector_3_01edit__distance__scoring__tag_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemeselector_3c_20smith_5fwaterman_5fscoring_5ftag_20_3e',['ScoringSchemeSelector&lt; smith_waterman_scoring_tag &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeSelector_3_01smith__waterman__scoring__tag_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag',['ScoringSchemeTag',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeTag.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag_3c_20editdistancescoringscheme_20_3e',['ScoringSchemeTag&lt; EditDistanceScoringScheme &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeTag_3_01EditDistanceScoringScheme_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag_3c_20smithwatermanscoringscheme_3c_20mmcost_2c_20ncost_20_3e_20_3e',['ScoringSchemeTag&lt; SmithWatermanScoringScheme&lt; MMCost, NCost &gt; &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1ScoringSchemeTag_3_01SmithWatermanScoringScheme_3_01MMCost_00_01NCost_01_4_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['seanalyzer',['SEAnalyzer',['../structnvbio_1_1alndiff_1_1SEAnalyzer.html',1,'nvbio::alndiff']]],
  ['seed_5fmapper',['seed_mapper',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20approx_5fmapping_20_3e',['seed_mapper&lt; APPROX_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01APPROX__MAPPING_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20case_5fpruning_5fmapping_20_3e',['seed_mapper&lt; CASE_PRUNING_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01CASE__PRUNING__MAPPING_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20exact_5fmapping_20_3e',['seed_mapper&lt; EXACT_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01EXACT__MAPPING_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seedhit',['SeedHit',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHit.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearray',['SeedHitDequeArray',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHitDequeArray.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearraydevicestorage',['SeedHitDequeArrayDeviceStorage',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHitDequeArrayDeviceStorage.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearraydeviceview',['SeedHitDequeArrayDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHitDequeArrayDeviceView.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearrayhoststorage',['SeedHitDequeArrayHostStorage',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHitDequeArrayHostStorage.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequereference',['SeedHitDequeReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1SeedHitDequeReference.html',1,'nvbio::bowtie2::cuda']]],
  ['select_5fdispatch',['select_dispatch',['../structnvbio_1_1aln_1_1select__dispatch.html',1,'nvbio::aln']]],
  ['select_5fdispatch_3c_20band_5flen_2c_20simd4u8_20_3e',['select_dispatch&lt; BAND_LEN, simd4u8 &gt;',['../structnvbio_1_1aln_1_1select__dispatch_3_01BAND__LEN_00_01simd4u8_01_4.html',1,'nvbio::aln']]],
  ['selectbestapproxcontext',['SelectBestApproxContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1SelectBestApproxContext.html',1,'nvbio::bowtie2::cuda']]],
  ['selector',['selector',['../structcufmi_1_1compound__sequence_1_1selector.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_200_20_3e',['selector&lt; 0 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_010_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_201_20_3e',['selector&lt; 1 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_011_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_202_20_3e',['selector&lt; 2 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_012_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_203_20_3e',['selector&lt; 3 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_013_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_204_20_3e',['selector&lt; 4 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_014_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_205_20_3e',['selector&lt; 5 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_015_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_206_20_3e',['selector&lt; 6 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_016_01_4.html',1,'cufmi::compound_sequence']]],
  ['selector_3c_207_20_3e',['selector&lt; 7 &gt;',['../structcufmi_1_1compound__sequence_1_1selector_3_017_01_4.html',1,'cufmi::compound_sequence']]],
  ['seqfinder',['SeqFinder',['../structnvbio_1_1io_1_1SeqFinder.html',1,'nvbio::io']]],
  ['sequential_5flayout',['sequential_layout',['../structcufmi_1_1sequential__layout.html',1,'cufmi']]],
  ['servermappedfile',['ServerMappedFile',['../structnvbio_1_1ServerMappedFile.html',1,'nvbio']]],
  ['sharedcount',['SharedCount',['../classnvbio_1_1internals_1_1SharedCount.html',1,'nvbio::internals']]],
  ['sharedcount_3c_20nvbio_3a_3aatomicint32_20_3e',['SharedCount&lt; nvbio::AtomicInt32 &gt;',['../classnvbio_1_1internals_1_1SharedCount.html',1,'nvbio::internals']]],
  ['sharedpointer',['SharedPointer',['../classnvbio_1_1SharedPointer.html',1,'nvbio']]],
  ['sharedpointer_3c_20nvbio_3a_3amutex_3a_3aimpl_2c_20nvbio_3a_3aatomicint32_20_3e',['SharedPointer&lt; nvbio::Mutex::Impl, nvbio::AtomicInt32 &gt;',['../classnvbio_1_1SharedPointer.html',1,'nvbio']]],
  ['sharedpointer_3c_20nvbio_3a_3athreadbase_3a_3aimpl_2c_20nvbio_3a_3aatomicint32_20_3e',['SharedPointer&lt; nvbio::ThreadBase::Impl, nvbio::AtomicInt32 &gt;',['../classnvbio_1_1SharedPointer.html',1,'nvbio']]],
  ['sharedpointertraits',['SharedPointerTraits',['../structnvbio_1_1internals_1_1SharedPointerTraits.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20_3e',['SharedPointerTraits&lt; void &gt;',['../structnvbio_1_1internals_1_1SharedPointerTraits_3_01void_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20const_20_20_3e',['SharedPointerTraits&lt; void const  &gt;',['../structnvbio_1_1internals_1_1SharedPointerTraits_3_01void_01const_01_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20const_20volatile_20_3e',['SharedPointerTraits&lt; void const volatile &gt;',['../structnvbio_1_1internals_1_1SharedPointerTraits_3_01void_01const_01volatile_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20volatile_20_3e',['SharedPointerTraits&lt; void volatile &gt;',['../structnvbio_1_1internals_1_1SharedPointerTraits_3_01void_01volatile_01_4.html',1,'nvbio::internals']]],
  ['signed_5ftype',['signed_type',['../structnvbio_1_1signed__type.html',1,'nvbio']]],
  ['signed_5ftype_3c_20int32_20_3e',['signed_type&lt; int32 &gt;',['../structnvbio_1_1signed__type_3_01int32_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20int64_20_3e',['signed_type&lt; int64 &gt;',['../structnvbio_1_1signed__type_3_01int64_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20uint32_20_3e',['signed_type&lt; uint32 &gt;',['../structnvbio_1_1signed__type_3_01uint32_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20uint64_20_3e',['signed_type&lt; uint64 &gt;',['../structnvbio_1_1signed__type_3_01uint64_01_4.html',1,'nvbio']]],
  ['simd4u8',['simd4u8',['../structnvbio_1_1simd4u8.html',1,'nvbio']]],
  ['simplegotohscheme',['SimpleGotohScheme',['../structnvbio_1_1aln_1_1SimpleGotohScheme.html',1,'nvbio::aln']]],
  ['simplesmithwatermanscheme',['SimpleSmithWatermanScheme',['../structnvbio_1_1aln_1_1SimpleSmithWatermanScheme.html',1,'nvbio::aln']]],
  ['smith_5fwaterman_5fscoring_5ftag',['smith_waterman_scoring_tag',['../structnvbio_1_1bowtie2_1_1cuda_1_1smith__waterman__scoring__tag.html',1,'nvbio::bowtie2::cuda']]],
  ['smithwatermanaligner',['SmithWatermanAligner',['../structnvbio_1_1aln_1_1SmithWatermanAligner.html',1,'nvbio::aln']]],
  ['smithwatermancheckpointcontext',['SmithWatermanCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1SmithWatermanCheckpointContext.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermancheckpointedscoringcontext',['SmithWatermanCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1SmithWatermanCheckpointedScoringContext.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermanscoringcontext',['SmithWatermanScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1SmithWatermanScoringContext.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermanscoringscheme',['SmithWatermanScoringScheme',['../structnvbio_1_1bowtie2_1_1cuda_1_1SmithWatermanScoringScheme.html',1,'nvbio::bowtie2::cuda']]],
  ['smithwatermansubmatrixcontext',['SmithWatermanSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1SmithWatermanSubmatrixContext.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermantag',['SmithWatermanTag',['../structnvbio_1_1aln_1_1SmithWatermanTag.html',1,'nvbio::aln']]],
  ['sortbuffers',['SortBuffers',['../structnvbio_1_1cuda_1_1SortBuffers.html',1,'nvbio::cuda']]],
  ['sorteddictionarynode',['SortedDictionaryNode',['../structnvbio_1_1SortedDictionaryNode.html',1,'nvbio']]],
  ['sorteddictionarysuffixtrie',['SortedDictionarySuffixTrie',['../structnvbio_1_1SortedDictionarySuffixTrie.html',1,'nvbio']]],
  ['sortenactor',['SortEnactor',['../structnvbio_1_1cuda_1_1SortEnactor.html',1,'nvbio::cuda']]],
  ['source_5fdispatch',['source_dispatch',['../structnvbio_1_1copy__dispatch_1_1source__dispatch.html',1,'nvbio::copy_dispatch']]],
  ['sparse_5fstring_5fset_5ftag',['sparse_string_set_tag',['../structnvbio_1_1sparse__string__set__tag.html',1,'nvbio']]],
  ['sparsestringset',['SparseStringSet',['../structnvbio_1_1SparseStringSet.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple',['SSA_index_multiple',['../structnvbio_1_1SSA__index__multiple.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple_5fcontext',['SSA_index_multiple_context',['../structnvbio_1_1SSA__index__multiple__context.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple_5fdevice',['SSA_index_multiple_device',['../structnvbio_1_1SSA__index__multiple__device.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple',['SSA_value_multiple',['../structnvbio_1_1SSA__value__multiple.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple_5fcontext',['SSA_value_multiple_context',['../structnvbio_1_1SSA__value__multiple__context.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple_5fdevice',['SSA_value_multiple_device',['../structnvbio_1_1SSA__value__multiple__device.html',1,'nvbio']]],
  ['stackinfo3',['stackinfo3',['../structdivsufsortxx_1_1helper_1_1stackinfo3.html',1,'divsufsortxx::helper']]],
  ['stackinfo4',['stackinfo4',['../structdivsufsortxx_1_1helper_1_1stackinfo4.html',1,'divsufsortxx::helper']]],
  ['stagedalignmentunitbase',['StagedAlignmentUnitBase',['../structnvbio_1_1aln_1_1StagedAlignmentUnitBase.html',1,'nvbio::aln']]],
  ['stagedalignmentunitbase_3c_20stream_5ftype_2c_20bandedscoreunit_3c_20band_5flen_2c_20stream_5ftype_20_3e_20_3e',['StagedAlignmentUnitBase&lt; stream_type, BandedScoreUnit&lt; BAND_LEN, stream_type &gt; &gt;',['../structnvbio_1_1aln_1_1StagedAlignmentUnitBase.html',1,'nvbio::aln']]],
  ['stagedalignmentunitbase_3c_20stream_5ftype_2c_20stagedscoreunit_3c_20stream_5ftype_20_3e_20_3e',['StagedAlignmentUnitBase&lt; stream_type, StagedScoreUnit&lt; stream_type &gt; &gt;',['../structnvbio_1_1aln_1_1StagedAlignmentUnitBase.html',1,'nvbio::aln']]],
  ['stagedscoreunit',['StagedScoreUnit',['../structnvbio_1_1aln_1_1StagedScoreUnit.html',1,'nvbio::aln']]],
  ['stagedthreadparallelscheduler',['StagedThreadParallelScheduler',['../structnvbio_1_1aln_1_1StagedThreadParallelScheduler.html',1,'nvbio::aln']]],
  ['static_5fcast_5fmarker',['static_cast_marker',['../structnvbio_1_1internals_1_1static__cast__marker.html',1,'nvbio::internals']]],
  ['static_5ftree_5fdesc_5fs',['static_tree_desc_s',['../structstatic__tree__desc__s.html',1,'']]],
  ['stats',['Stats',['../structnvbio_1_1alndiff_1_1Stats.html',1,'nvbio::alndiff']]],
  ['stats',['Stats',['../structnvbio_1_1bowtie2_1_1cuda_1_1Stats.html',1,'nvbio::bowtie2::cuda']]],
  ['stats_3c_20higher_2c_20log_20_3e',['Stats&lt; HIGHER, LOG &gt;',['../structnvbio_1_1alndiff_1_1Stats.html',1,'nvbio::alndiff']]],
  ['stats_3c_20lower_2c_20linear_20_3e',['Stats&lt; LOWER, LINEAR &gt;',['../structnvbio_1_1alndiff_1_1Stats.html',1,'nvbio::alndiff']]],
  ['statspartition',['StatsPartition',['../structnvbio_1_1alndiff_1_1StatsPartition.html',1,'nvbio::alndiff']]],
  ['stream_5ftraits',['stream_traits',['../structnvbio_1_1stream__traits.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20const_20t_20_2a_20_3e',['stream_traits&lt; const T * &gt;',['../structnvbio_1_1stream__traits_3_01const_01T_01_5_01_4.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20packedstream_3c_20inputstream_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20indextype_20_3e_20_3e',['stream_traits&lt; PackedStream&lt; InputStream, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, IndexType &gt; &gt;',['../structnvbio_1_1stream__traits_3_01PackedStream_3_01InputStream_00_01SymbolType_00_01SYMBOL__SIZE956ce6e18c14f8c80a1df66f9dbd69b8.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20packedstreamiterator_3c_20stream_20_3e_20_3e',['stream_traits&lt; PackedStreamIterator&lt; Stream &gt; &gt;',['../structnvbio_1_1stream__traits_3_01PackedStreamIterator_3_01Stream_01_4_01_4.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20t_20_2a_20_3e',['stream_traits&lt; T * &gt;',['../structnvbio_1_1stream__traits_3_01T_01_5_01_4.html',1,'nvbio']]],
  ['streamadapter',['StreamAdapter',['../structnvbio_1_1bowtie2_1_1cuda_1_1StreamAdapter.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase',['StreamAdapterBase',['../structnvbio_1_1bowtie2_1_1cuda_1_1StreamAdapterBase.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase_3c_20iterator_2c_20uint32_20_3e',['StreamAdapterBase&lt; Iterator, uint32 &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1StreamAdapterBase_3_01Iterator_00_01uint32_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase_3c_20iterator_2c_20uint4_20_3e',['StreamAdapterBase&lt; Iterator, uint4 &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1StreamAdapterBase_3_01Iterator_00_01uint4_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['streamremapper',['StreamRemapper',['../structnvbio_1_1StreamRemapper.html',1,'nvbio']]],
  ['streamtransform',['StreamTransform',['../structnvbio_1_1StreamTransform.html',1,'nvbio']]],
  ['strided_5fiterator',['strided_iterator',['../structnvbio_1_1strided__iterator.html',1,'nvbio']]],
  ['strided_5flayout',['strided_layout',['../structcufmi_1_1strided__layout.html',1,'cufmi']]],
  ['strided_5fpacked_5fstring_5fset_5ftag',['strided_packed_string_set_tag',['../structnvbio_1_1strided__packed__string__set__tag.html',1,'nvbio']]],
  ['strided_5fstring_5fset_5ftag',['strided_string_set_tag',['../structnvbio_1_1strided__string__set__tag.html',1,'nvbio']]],
  ['stridedpackedstringset',['StridedPackedStringSet',['../structnvbio_1_1StridedPackedStringSet.html',1,'nvbio']]],
  ['stridedstringset',['StridedStringSet',['../structnvbio_1_1StridedStringSet.html',1,'nvbio']]],
  ['strings_5ftype',['strings_type',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1AlignmentStreamBase_1_1strings__type.html',1,'nvbio::bowtie2::cuda::detail::AlignmentStreamBase']]],
  ['strings_5ftype',['strings_type',['../structnvbio_1_1aln_1_1priv_1_1AlignmentStream_1_1strings__type.html',1,'nvbio::aln::priv::AlignmentStream']]],
  ['substring_5fwrapper',['substring_wrapper',['../classdivsufsortxx_1_1substring_1_1substring__wrapper.html',1,'divsufsortxx::substring']]],
  ['suffixtrie',['SuffixTrie',['../structnvbio_1_1SuffixTrie.html',1,'nvbio']]],
  ['sumtree',['SumTree',['../structnvbio_1_1SumTree.html',1,'nvbio']]],
  ['sw_5falignment_5fscore_5fdispatch',['sw_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1sw__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['sw_5falignment_5fscore_5fdispatch',['sw_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1sw__alignment__score__dispatch.html',1,'nvbio::aln::priv::banded']]],
  ['sw_5fbandlen_5fselector',['sw_bandlen_selector',['../structnvbio_1_1aln_1_1priv_1_1sw__bandlen__selector.html',1,'nvbio::aln::priv']]],
  ['sw_5fbandlen_5fselector_3c_20type_2c_20dim_2c_20simd4u8_20_3e',['sw_bandlen_selector&lt; TYPE, DIM, simd4u8 &gt;',['../structnvbio_1_1aln_1_1priv_1_1sw__bandlen__selector_3_01TYPE_00_01DIM_00_01simd4u8_01_4.html',1,'nvbio::aln::priv']]],
  ['swcheckpointcontext',['SWCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1SWCheckpointContext.html',1,'nvbio::aln::priv']]],
  ['swcheckpointedscoringcontext',['SWCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1SWCheckpointedScoringContext.html',1,'nvbio::aln::priv']]],
  ['swscoringcontext',['SWScoringContext',['../structnvbio_1_1aln_1_1priv_1_1SWScoringContext.html',1,'nvbio::aln::priv']]],
  ['swsubmatrixcontext',['SWSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1SWSubmatrixContext.html',1,'nvbio::aln::priv']]],
  ['syncblocks',['syncblocks',['../structnvbio_1_1cuda_1_1syncblocks.html',1,'nvbio::cuda']]],
  ['syncblocks_5fstorage',['syncblocks_storage',['../structnvbio_1_1cuda_1_1syncblocks__storage.html',1,'nvbio::cuda']]]
];
