var searchData=
[
  ['backtracker',['Backtracker',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1Backtracker.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['backtracker_3c_20io_3a_3acigar_20_2a_20_3e',['Backtracker&lt; io::Cigar * &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1Backtracker.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bad_5falloc',['bad_alloc',['../structnvbio_1_1bad__alloc.html',1,'nvbio']]],
  ['bam_5falignment',['BAM_alignment',['../structnvbio_1_1io_1_1BAM__alignment.html',1,'nvbio::io']]],
  ['bam_5falignment_5fdata_5fblock',['BAM_alignment_data_block',['../structnvbio_1_1io_1_1BAM__alignment__data__block.html',1,'nvbio::io']]],
  ['bam_5fheader',['BAM_header',['../structnvbio_1_1io_1_1BAM__header.html',1,'nvbio::io']]],
  ['bam_5freference',['BAM_reference',['../structnvbio_1_1io_1_1BAM__reference.html',1,'nvbio::io']]],
  ['bamalignment',['BamAlignment',['../structBamTools_1_1BamAlignment.html',1,'BamTools']]],
  ['bamalignmentstream',['BAMAlignmentStream',['../structnvbio_1_1alndiff_1_1BAMAlignmentStream.html',1,'nvbio::alndiff']]],
  ['bamoutput',['BamOutput',['../structnvbio_1_1io_1_1BamOutput.html',1,'nvbio::io']]],
  ['bamreader',['BamReader',['../classBamTools_1_1BamReader.html',1,'BamTools']]],
  ['bamreaderprivate',['BamReaderPrivate',['../structBamReader_1_1BamReaderPrivate.html',1,'BamTools::BamReader']]],
  ['bamwriter',['BamWriter',['../classBamTools_1_1BamWriter.html',1,'BamTools']]],
  ['bamwriterprivate',['BamWriterPrivate',['../structBamWriter_1_1BamWriterPrivate.html',1,'BamTools::BamWriter']]],
  ['band_5freg',['Band_reg',['../structcufmi_1_1bowtie2_1_1cuda_1_1Band__reg.html',1,'cufmi::bowtie2::cuda']]],
  ['band_5fvec',['Band_vec',['../structcufmi_1_1bowtie2_1_1cuda_1_1Band__vec.html',1,'cufmi::bowtie2::cuda']]],
  ['banded_5falignment_5fcheckpointed_5fdispatch',['banded_alignment_checkpointed_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded__alignment__checkpointed__dispatch.html',1,'nvbio::aln::priv']]],
  ['banded_5falignment_5fscore_5fdispatch',['banded_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['bandedscoreunit',['BandedScoreUnit',['../structnvbio_1_1aln_1_1BandedScoreUnit.html',1,'nvbio::aln']]],
  ['base_5frep_5ftag',['base_rep_tag',['../structnvbio_1_1simd4u8_1_1base__rep__tag.html',1,'nvbio::simd4u8']]],
  ['basescoringpipelinestate',['BaseScoringPipelineState',['../structnvbio_1_1bowtie2_1_1cuda_1_1BaseScoringPipelineState.html',1,'nvbio::bowtie2::cuda']]],
  ['batchedalignmentscore',['BatchedAlignmentScore',['../structnvbio_1_1aln_1_1BatchedAlignmentScore.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20stagedthreadparallelscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, StagedThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedAlignmentScore_3_01stream__type_00_01StagedThreadParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20threadparallelscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, ThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedAlignmentScore_3_01stream__type_00_01ThreadParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20warpparallelscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, WarpParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedAlignmentScore_3_01stream__type_00_01WarpParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmenttraceback',['BatchedAlignmentTraceback',['../structnvbio_1_1aln_1_1BatchedAlignmentTraceback.html',1,'nvbio::aln']]],
  ['batchedalignmenttraceback_3c_20checkpoints_2c_20stream_5ftype_2c_20threadparallelscheduler_20_3e',['BatchedAlignmentTraceback&lt; CHECKPOINTS, stream_type, ThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedAlignmentTraceback_3_01CHECKPOINTS_00_01stream__type_00_01ThreadParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore',['BatchedBandedAlignmentScore',['../structnvbio_1_1aln_1_1BatchedBandedAlignmentScore.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore_3c_20band_5flen_2c_20stream_5ftype_2c_20stagedthreadparallelscheduler_20_3e',['BatchedBandedAlignmentScore&lt; BAND_LEN, stream_type, StagedThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedBandedAlignmentScore_3_01BAND__LEN_00_01stream__type_00_01StagedThreadParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore_3c_20band_5flen_2c_20stream_5ftype_2c_20threadparallelscheduler_20_3e',['BatchedBandedAlignmentScore&lt; BAND_LEN, stream_type, ThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedBandedAlignmentScore_3_01BAND__LEN_00_01stream__type_00_01ThreadParallelScheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedbandedalignmenttraceback',['BatchedBandedAlignmentTraceback',['../structnvbio_1_1aln_1_1BatchedBandedAlignmentTraceback.html',1,'nvbio::aln']]],
  ['batchedbandedalignmenttraceback_3c_20band_5flen_2c_20checkpoints_2c_20stream_5ftype_2c_20threadparallelscheduler_20_3e',['BatchedBandedAlignmentTraceback&lt; BAND_LEN, CHECKPOINTS, stream_type, ThreadParallelScheduler &gt;',['../structnvbio_1_1aln_1_1BatchedBandedAlignmentTraceback_3_01BAND__LEN_00_01CHECKPOINTS_00_01stream8a0cf825c168d910f07d2d590f70e24f.html',1,'nvbio::aln']]],
  ['best2sink',['Best2Sink',['../structnvbio_1_1aln_1_1Best2Sink.html',1,'nvbio::aln']]],
  ['bestalignments',['BestAlignments',['../structnvbio_1_1io_1_1BestAlignments.html',1,'nvbio::io']]],
  ['bestanchorscorestream',['BestAnchorScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1BestAnchorScoreStream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestapproxscoringpipelinestate',['BestApproxScoringPipelineState',['../structnvbio_1_1bowtie2_1_1cuda_1_1BestApproxScoringPipelineState.html',1,'nvbio::bowtie2::cuda']]],
  ['bestoppositescorestream',['BestOppositeScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1BestOppositeScoreStream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestpairedalignments',['BestPairedAlignments',['../structnvbio_1_1io_1_1BestPairedAlignments.html',1,'nvbio::io']]],
  ['bestscorestream',['BestScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1BestScoreStream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestsink',['BestSink',['../structnvbio_1_1aln_1_1BestSink.html',1,'nvbio::aln']]],
  ['bestsink_3c_20int32_20_3e',['BestSink&lt; int32 &gt;',['../structnvbio_1_1aln_1_1BestSink.html',1,'nvbio::aln']]],
  ['bestsink_3c_20simd4u8_20_3e',['BestSink&lt; simd4u8 &gt;',['../structnvbio_1_1aln_1_1BestSink_3_01simd4u8_01_4.html',1,'nvbio::aln']]],
  ['besttracebackstream',['BestTracebackStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1BestTracebackStream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bgzf_5fextra_5fdata',['bgzf_extra_data',['../structnvbio_1_1io_1_1BGZFCompressor_1_1bgzf__extra__data.html',1,'nvbio::io::BGZFCompressor']]],
  ['bgzfcompressor',['BGZFCompressor',['../structnvbio_1_1io_1_1BGZFCompressor.html',1,'nvbio::io']]],
  ['bgzfdata',['BgzfData',['../structBamTools_1_1BgzfData.html',1,'BamTools']]],
  ['bgzfthread',['BgzfThread',['../structBamTools_1_1BgzfThread.html',1,'BamTools']]],
  ['binary_5fswitch',['binary_switch',['../structnvbio_1_1binary__switch.html',1,'nvbio']]],
  ['binary_5fswitch_3c_20a_2c_20b_2c_200_20_3e',['binary_switch&lt; A, B, 0 &gt;',['../structnvbio_1_1binary__switch_3_01A_00_01B_00_010_01_4.html',1,'nvbio']]],
  ['binarycast',['BinaryCast',['../unionnvbio_1_1BinaryCast.html',1,'nvbio']]],
  ['bind_5ffirst_5ffunctor',['bind_first_functor',['../structnvbio_1_1bind__first__functor.html',1,'nvbio']]],
  ['bind_5fsecond_5ffunctor',['bind_second_functor',['../structnvbio_1_1bind__second__functor.html',1,'nvbio']]],
  ['block_5fstrided_5fiterator',['block_strided_iterator',['../structnvbio_1_1block__strided__iterator.html',1,'nvbio']]],
  ['bloom_5ffilter',['bloom_filter',['../structnvbio_1_1bloom__filter.html',1,'nvbio']]],
  ['bns_5ffiles_5fmismatch',['bns_files_mismatch',['../structnvbio_1_1bns__files__mismatch.html',1,'nvbio']]],
  ['bns_5ffopen_5ffailure',['bns_fopen_failure',['../structnvbio_1_1bns__fopen__failure.html',1,'nvbio']]],
  ['bnt',['BNT',['../structnvbio_1_1io_1_1BNT.html',1,'nvbio::io']]],
  ['bntamb',['BNTAmb',['../structnvbio_1_1io_1_1BNTAmb.html',1,'nvbio::io']]],
  ['bntamb',['BNTAmb',['../structnvbio_1_1BNTAmb.html',1,'nvbio']]],
  ['bntann',['BNTAnn',['../structnvbio_1_1io_1_1BNTAnn.html',1,'nvbio::io']]],
  ['bntanndata',['BNTAnnData',['../structnvbio_1_1BNTAnnData.html',1,'nvbio']]],
  ['bntanninfo',['BNTAnnInfo',['../structnvbio_1_1BNTAnnInfo.html',1,'nvbio']]],
  ['bntinfo',['BNTInfo',['../structnvbio_1_1io_1_1BNTInfo.html',1,'nvbio::io']]],
  ['bntinfo',['BNTInfo',['../structnvbio_1_1BNTInfo.html',1,'nvbio']]],
  ['bntseq',['BNTSeq',['../structnvbio_1_1BNTSeq.html',1,'nvbio']]],
  ['bntseqloader',['BNTSeqLoader',['../structnvbio_1_1BNTSeqLoader.html',1,'nvbio']]],
  ['bntseqpod',['BNTSeqPOD',['../structnvbio_1_1io_1_1BNTSeqPOD.html',1,'nvbio::io']]],
  ['bntseqvec',['BNTSeqVec',['../structnvbio_1_1io_1_1BNTSeqVec.html',1,'nvbio::io']]],
  ['body_5fobject',['body_object',['../structnvbio_1_1html_1_1body__object.html',1,'nvbio::html']]],
  ['booleanstats',['BooleanStats',['../structnvbio_1_1alndiff_1_1BooleanStats.html',1,'nvbio::alndiff']]],
  ['bowtiemapq',['BowtieMapq',['../structnvbio_1_1bowtie2_1_1cuda_1_1BowtieMapq.html',1,'nvbio::bowtie2::cuda']]],
  ['bowtiemapq2',['BowtieMapq2',['../structnvbio_1_1bowtie2_1_1cuda_1_1BowtieMapq2.html',1,'nvbio::bowtie2::cuda']]],
  ['bowtiemapq3',['BowtieMapq3',['../structnvbio_1_1bowtie2_1_1cuda_1_1BowtieMapq3.html',1,'nvbio::bowtie2::cuda']]]
];
