var searchData=
[
  ['databuffer',['DataBuffer',['../structnvbio_1_1io_1_1_data_buffer.html',1,'nvbio::io']]],
  ['dbgalignment',['DbgAlignment',['../structnvbio_1_1io_1_1_debug_output_1_1_dbg_alignment.html',1,'nvbio::io::DebugOutput']]],
  ['dbginfo',['DbgInfo',['../structnvbio_1_1io_1_1_debug_output_1_1_dbg_info.html',1,'nvbio::io::DebugOutput']]],
  ['debugalignmentstream',['DebugAlignmentStream',['../structnvbio_1_1alndiff_1_1_debug_alignment_stream.html',1,'nvbio::alndiff']]],
  ['debugoutput',['DebugOutput',['../structnvbio_1_1io_1_1_debug_output.html',1,'nvbio::io']]],
  ['debugstate',['DebugState',['../structnvbio_1_1bowtie2_1_1cuda_1_1_debug_state.html',1,'nvbio::bowtie2::cuda']]],
  ['defaultmover',['DefaultMover',['../structnvbio_1_1cuda_1_1_default_mover.html',1,'nvbio::cuda']]],
  ['deinterleaved_5fiterator',['deinterleaved_iterator',['../structnvbio_1_1deinterleaved__iterator.html',1,'nvbio']]],
  ['deleter',['Deleter',['../structnvbio_1_1internals_1_1_deleter.html',1,'nvbio::internals']]],
  ['device_5fview_5fsubtype',['device_view_subtype',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20const_20t_20_2a_20_3e',['device_view_subtype&lt; const T * &gt;',['../structnvbio_1_1device__view__subtype_3_01const_01_t_01_5_01_4.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3aindex_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::index_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3aloc_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::loc_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3ascore_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::score_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3aseed_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::seed_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3asink_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::sink_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20hitqueues_3a_3assa_5fstorage_5ftype_20_3e',['device_view_subtype&lt; HitQueues::ssa_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20null_5ftype_20_3e',['device_view_subtype&lt; null_type &gt;',['../structnvbio_1_1device__view__subtype_3_01null__type_01_4.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20readhitsindex_3a_3alinks_5fstorage_5ftype_20_3e',['device_view_subtype&lt; ReadHitsIndex::links_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20scoringqueues_3a_3aactive_5freads_5fstorage_5ftype_20_3e',['device_view_subtype&lt; ScoringQueues::active_reads_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20scoringqueues_3a_3ahits_5fstorage_5ftype_20_3e',['device_view_subtype&lt; ScoringQueues::hits_storage_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20scoringqueues_3a_3apool_5ftype_20_3e',['device_view_subtype&lt; ScoringQueues::pool_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20scoringqueues_3a_3aread_5fhits_5findex_5ftype_20_3e',['device_view_subtype&lt; ScoringQueues::read_hits_index_type &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20t_20_2a_20_3e',['device_view_subtype&lt; T * &gt;',['../structnvbio_1_1device__view__subtype_3_01_t_01_5_01_4.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20thrust_3a_3adevice_5fvector_3c_20float_20_3e_20_3e',['device_view_subtype&lt; thrust::device_vector&lt; float &gt; &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20thrust_3a_3adevice_5fvector_3c_20seedhit_20_3e_20_3e',['device_view_subtype&lt; thrust::device_vector&lt; SeedHit &gt; &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20thrust_3a_3adevice_5fvector_3c_20t_20_3e_20_3e',['device_view_subtype&lt; thrust::device_vector&lt; T &gt; &gt;',['../structnvbio_1_1device__view__subtype_3_01thrust_1_1device__vector_3_01_t_01_4_01_4.html',1,'nvbio']]],
  ['device_5fview_5fsubtype_3c_20thrust_3a_3adevice_5fvector_3c_20uint32_20_3e_20_3e',['device_view_subtype&lt; thrust::device_vector&lt; uint32 &gt; &gt;',['../structnvbio_1_1device__view__subtype.html',1,'nvbio']]],
  ['devicecigararray',['DeviceCigarArray',['../structnvbio_1_1io_1_1_device_cigar_array.html',1,'nvbio::io']]],
  ['devicevectorarray',['DeviceVectorArray',['../structnvbio_1_1cuda_1_1_device_vector_array.html',1,'nvbio::cuda']]],
  ['devicevectorarray_3c_20io_3a_3acigar_20_3e',['DeviceVectorArray&lt; io::Cigar &gt;',['../structnvbio_1_1cuda_1_1_device_vector_array.html',1,'nvbio::cuda']]],
  ['devicevectorarray_3c_20io_3a_3anvbio_3a_3aio_3a_3acigar_20_3e',['DeviceVectorArray&lt; io::nvbio::io::Cigar &gt;',['../structnvbio_1_1cuda_1_1_device_vector_array.html',1,'nvbio::cuda']]],
  ['devicevectorarray_3c_20uint8_20_3e',['DeviceVectorArray&lt; uint8 &gt;',['../structnvbio_1_1cuda_1_1_device_vector_array.html',1,'nvbio::cuda']]],
  ['devicevectorarrayview',['DeviceVectorArrayView',['../structnvbio_1_1cuda_1_1_device_vector_array_view.html',1,'nvbio::cuda']]],
  ['devicevectorarrayview_3c_20io_3a_3acigar_20_3e',['DeviceVectorArrayView&lt; io::Cigar &gt;',['../structnvbio_1_1cuda_1_1_device_vector_array_view.html',1,'nvbio::cuda']]],
  ['devicevectorarrayview_3c_20uint8_20_3e',['DeviceVectorArrayView&lt; uint8 &gt;',['../structnvbio_1_1cuda_1_1_device_vector_array_view.html',1,'nvbio::cuda']]],
  ['direction_5fvector_5ftraits',['direction_vector_traits',['../structnvbio_1_1aln_1_1direction__vector__traits.html',1,'nvbio::aln']]],
  ['direction_5fvector_5ftraits_3c_20gotohaligner_3c_20type_2c_20scoring_5ftype_20_3e_20_3e',['direction_vector_traits&lt; GotohAligner&lt; TYPE, scoring_type &gt; &gt;',['../structnvbio_1_1aln_1_1direction__vector__traits_3_01_gotoh_aligner_3_01_t_y_p_e_00_01scoring__type_01_4_01_4.html',1,'nvbio::aln']]],
  ['dispatch_5frank',['dispatch_rank',['../structnvbio_1_1dispatch__rank.html',1,'nvbio']]],
  ['dispatch_5frank_3c_202_2c_2064_2c_20packedstream_3c_20textstorage_2c_20uint8_2c_202u_2c_20true_20_3e_2c_20occiterator_2c_20counttable_2c_20uint4_2c_20uint4_20_3e',['dispatch_rank&lt; 2, 64, PackedStream&lt; TextStorage, uint8, 2u, true &gt;, OccIterator, CountTable, uint4, uint4 &gt;',['../structnvbio_1_1dispatch__rank_3_012_00_0164_00_01_packed_stream_3_01_text_storage_00_01uint8_00_69a404735257d2d95bc8159a8258ed21.html',1,'nvbio']]],
  ['dispatch_5frank_3c_202_2c_20k_2c_20packedstream_3c_20textstorage_2c_20uint8_2c_202u_2c_20true_2c_20index_5ftype_20_3e_2c_20occiterator_2c_20counttable_2c_20word_5ftype_2c_20index_5ftype_20_3e',['dispatch_rank&lt; 2, K, PackedStream&lt; TextStorage, uint8, 2u, true, index_type &gt;, OccIterator, CountTable, word_type, index_type &gt;',['../structnvbio_1_1dispatch__rank_3_012_00_01_k_00_01_packed_stream_3_01_text_storage_00_01uint8_00_11de7cfb53a5da4b9758128a89011542.html',1,'nvbio']]],
  ['dynamic_5fcast_5fmarker',['dynamic_cast_marker',['../structnvbio_1_1internals_1_1dynamic__cast__marker.html',1,'nvbio::internals']]]
];
