var searchData=
[
  ['rank_5fdictionary',['rank_dictionary',['../structnvbio_1_1rank__dictionary.html',1,'nvbio']]],
  ['rank_5fword_5ftraits',['rank_word_traits',['../structnvbio_1_1rank__word__traits.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_20uint32_20_3e',['rank_word_traits&lt; uint32 &gt;',['../structnvbio_1_1rank__word__traits_3_01uint32_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_20uint64_20_3e',['rank_word_traits&lt; uint64 &gt;',['../structnvbio_1_1rank__word__traits_3_01uint64_01_4.html',1,'nvbio']]],
  ['readdata',['ReadData',['../structnvbio_1_1io_1_1ReadData.html',1,'nvbio::io']]],
  ['readdatacuda',['ReadDataCUDA',['../structnvbio_1_1io_1_1ReadDataCUDA.html',1,'nvbio::io']]],
  ['readdatafile',['ReadDataFile',['../structnvbio_1_1io_1_1ReadDataFile.html',1,'nvbio::io']]],
  ['readdatafile_5fbam',['ReadDataFile_BAM',['../structnvbio_1_1io_1_1ReadDataFile__BAM.html',1,'nvbio::io']]],
  ['readdatafile_5ffastq_5fgz',['ReadDataFile_FASTQ_gz',['../structnvbio_1_1io_1_1ReadDataFile__FASTQ__gz.html',1,'nvbio::io']]],
  ['readdatafile_5ffastq_5fparser',['ReadDataFile_FASTQ_parser',['../structnvbio_1_1io_1_1ReadDataFile__FASTQ__parser.html',1,'nvbio::io']]],
  ['readdatafile_5fsam',['ReadDataFile_SAM',['../structnvbio_1_1io_1_1ReadDataFile__SAM.html',1,'nvbio::io']]],
  ['readdataram',['ReadDataRAM',['../structnvbio_1_1io_1_1ReadDataRAM.html',1,'nvbio::io']]],
  ['readdatastream',['ReadDataStream',['../structnvbio_1_1io_1_1ReadDataStream.html',1,'nvbio::io']]],
  ['readdataview',['ReadDataView',['../structnvbio_1_1io_1_1ReadDataView.html',1,'nvbio::io']]],
  ['readdataview_3c_20uint32_20_2a_2c_20uint32_20_2a_2c_20char_20_2a_2c_20char_20_2a_20_3e',['ReadDataView&lt; uint32 *, uint32 *, char *, char * &gt;',['../structnvbio_1_1io_1_1ReadDataView.html',1,'nvbio::io']]],
  ['readhitbinder',['ReadHitBinder',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitBinder.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitreference',['ReadHitReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitReference.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsbinder',['ReadHitsBinder',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitsBinder.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsindex',['ReadHitsIndex',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitsIndex.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsindexdeviceview',['ReadHitsIndexDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitsIndexDeviceView.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsreference',['ReadHitsReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReadHitsReference.html',1,'nvbio::bowtie2::cuda']]],
  ['readloader',['ReadLoader',['../structnvbio_1_1ReadLoader.html',1,'nvbio']]],
  ['readloader_3c_20read_5fbatch_5ftype_2c_20lmem_5fcache_5ftype_20_3e',['ReadLoader&lt; read_batch_type, lmem_cache_type &gt;',['../structnvbio_1_1ReadLoader.html',1,'nvbio']]],
  ['readstream',['ReadStream',['../structnvbio_1_1ReadStream.html',1,'nvbio']]],
  ['readstreamqualities',['ReadStreamQualities',['../structnvbio_1_1ReadStreamQualities.html',1,'nvbio']]],
  ['reducebestapproxcontext',['ReduceBestApproxContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReduceBestApproxContext.html',1,'nvbio::bowtie2::cuda']]],
  ['reducebestexactcontext',['ReduceBestExactContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1ReduceBestExactContext.html',1,'nvbio::bowtie2::cuda']]],
  ['refdata',['RefData',['../structBamTools_1_1RefData.html',1,'BamTools']]],
  ['refedit',['RefEdit',['../structBamTools_1_1RefEdit.html',1,'BamTools']]],
  ['reference_5fcache',['Reference_cache',['../structnvbio_1_1aln_1_1priv_1_1Reference__cache.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_2015u_20_3e',['Reference_cache&lt; 15u &gt;',['../structnvbio_1_1aln_1_1priv_1_1Reference__cache_3_0115u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_203u_20_3e',['Reference_cache&lt; 3u &gt;',['../structnvbio_1_1aln_1_1priv_1_1Reference__cache_3_013u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_205u_20_3e',['Reference_cache&lt; 5u &gt;',['../structnvbio_1_1aln_1_1priv_1_1Reference__cache_3_015u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_207u_20_3e',['Reference_cache&lt; 7u &gt;',['../structnvbio_1_1aln_1_1priv_1_1Reference__cache_3_017u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fmeta_5ftype',['reference_meta_type',['../structcufmi_1_1reference__meta__type.html',1,'cufmi']]],
  ['reference_5fmeta_5ftype_3c_20null_5ftype_20_3e',['reference_meta_type&lt; null_type &gt;',['../structcufmi_1_1reference__meta__type_3_01null__type_01_4.html',1,'cufmi']]],
  ['reference_5fsubtype',['reference_subtype',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20const_20t_20_2a_20_3e',['reference_subtype&lt; const T * &gt;',['../structnvbio_1_1reference__subtype_3_01const_01T_01_5_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20null_5ftype_20_3e',['reference_subtype&lt; null_type &gt;',['../structnvbio_1_1reference__subtype_3_01null__type_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20t_20_2a_20_3e',['reference_subtype&lt; T * &gt;',['../structnvbio_1_1reference__subtype_3_01T_01_5_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aindex_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::index_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aloc_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::loc_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3ascore_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::score_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aseed_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::seed_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3asink_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::sink_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3assa_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::ssa_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['referenceindex',['ReferenceIndex',['../structBamTools_1_1ReferenceIndex.html',1,'BamTools']]],
  ['reverse_5ffunctor',['reverse_functor',['../structnvbio_1_1reverse__functor.html',1,'nvbio']]],
  ['reversexform',['ReverseXform',['../structnvbio_1_1ReverseXform.html',1,'nvbio']]],
  ['roundedqualcost',['RoundedQualCost',['../structnvbio_1_1bowtie2_1_1cuda_1_1RoundedQualCost.html',1,'nvbio::bowtie2::cuda']]],
  ['runtime_5ferror',['runtime_error',['../structnvbio_1_1runtime__error.html',1,'nvbio']]]
];
